version: "3.7"

services:
  service:
    image: tlvlp/ddns-tls-service:1.1.0
    volumes:
      - tls_volume:/ddns_tls_service/tls:rw
      - /opt/ddns-tls-service/config:/ddns_tls_service/config:rw
      - /opt/ddns-tls-service/logs:/ddns_tls_service/logs:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    secrets:
      - MY_API_KEY_COMES_HERE
    environment:
      LOG_LEVEL_ROOT: 'INFO'
      CONFIG_FOLDER_PATH: '/ddns_tls_service/config'
      CONFIG_UPDATE_DELAY: '5000'
      DDNS_SERVICE_ACTIVE: 'true'
      DDNS_CHECK_SCHEDULE: '* */10 * * * *'
      TLS_CERT_SERVICE_ACTIVE: 'true'
      TLS_CERT_CHECK_SCHEDULE: '0 0 9 */1 * *'
      TLS_CERT_FOLDER_PATH: '/ddns_tls_service/tls'
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  tls_volume:
    name: "tls_volume"

secrets:
  MY_API_KEY_COMES_HERE:
    external: true



