version: "3.7"

services:
  service:
    image: tlvlp/ddns-tls-service:latest
    volumes:
      - tls_volume:/ddns_tls_service/tls:rw
      - /opt/ddns-tls-service/ddns_records:/ddns_tls_service/ddns_records:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    secrets:
      - MY_API_KEY_COMES_HERE
    environment:
      RECORDS_FILE_PATH: '/ddns_tls_service/ddns_records/ddns_records.json'
      RECORD_UPDATE_SCHEDULE: '*/5 * * * * *'
      IP_CHECK_SCHEDULE: '* */10 * * * *'
      EXTERNAL_IP_API_CSV: 'http://checkip.amazonaws.com,https://myexternalip.com/raw'
      LOG_LEVEL_ROOT: 'INFO'
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  tls_volume:
    name: "tls_volume"

secrets:
  MY_API_KEY_COMES_HERE:
    external: true



